use CompraVenta


CREATE TABLE TM_COMPANIA(
COM_ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
COM_NOM VARCHAR(150) ,
FECH_CREA DATETIME ,
EST INT 
)


CREATE TABLE TM_EMPRESA(
EMP_ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
COM_ID INT ,
EMP_NOM VARCHAR(150) ,
EMP_RUC VARCHAR(50) ,
FECH_CREA DATETIME ,
EST INT ,
CONSTRAINT FK_COM_ID 
	FOREIGN KEY (COM_ID)
	REFERENCES TM_COMPANIA (COM_ID)
)


CREATE TABLE TM_SUCURSAL(
SUC_ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
EMP_ID INT ,
SUC_NOM VARCHAR(150) ,
FECH_CREA DATETIME ,
EST INT ,
CONSTRAINT FK_EMP_ID 
	FOREIGN KEY (EMP_ID)
	REFERENCES TM_EMPRESA (EMP_ID)

)


CREATE TABLE TM_ROL(
ROL_ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
SUC_ID INT ,
ROL_NOM VARCHAR(50) ,
FECH_CREA DATETIME ,
EST INT ,

CONSTRAINT FK_SUC_ID 
	FOREIGN KEY (SUC_ID)
	REFERENCES TM_SUCURSAL (SUC_ID)
)


CREATE TABLE TM_USUARIO(
USU_ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
SUC_ID INT ,
ROL_ID INT ,
USU_NOM VARCHAR(150) ,
USU_APE VARCHAR(150) ,
USU_CORREO VARCHAR(150) ,
USU_DPI VARCHAR(50) ,
USU_TEL VARCHAR(50) ,
USU_PASS VARCHAR(50) ,
FECH_CREA DATETIME ,
EST INT ,

CONSTRAINT U_FK_SUC_ID 
	FOREIGN KEY (SUC_ID)
	REFERENCES TM_SUCURSAL (SUC_ID),

CONSTRAINT U_FK_ROL_ID 
	FOREIGN KEY (ROL_ID)
	REFERENCES TM_ROL (ROL_ID)
)


CREATE TABLE TM_CATEGORIA(
CAT_ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
SUC_ID INT ,
CAT_NOM VARCHAR(150) ,
FECH_CREA DATETIME ,
EST INT 

CONSTRAINT CAT_FK_SUC_ID 
	FOREIGN KEY (SUC_ID)
	REFERENCES TM_SUCURSAL (SUC_ID)
)


CREATE TABLE TM_MONEDA(
MON_ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
SUC_ID INT ,
MON_NOM VARCHAR(150) ,
FECH_CREA DATETIME ,
EST INT 

CONSTRAINT MON_FK_SUC_ID 
	FOREIGN KEY (SUC_ID)
	REFERENCES TM_SUCURSAL (SUC_ID)
)


CREATE TABLE TM_UNIDAD(
UND_ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
SUC_ID INT ,
UND_NOM VARCHAR(150) ,
FECH_CREA DATETIME ,
EST INT 

CONSTRAINT UND_FK_SUC_ID 
	FOREIGN KEY (SUC_ID)
	REFERENCES TM_SUCURSAL (SUC_ID)
)


CREATE TABLE TM_PRODUCTO(
PROD_ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
SUC_ID INT ,
CAT_ID INT  ,
PROD_NOM VARCHAR(150) ,
PROD_DESCRIP VARCHAR(150)  ,
UND_ID INT ,
MON_ID INT  ,
PROD_PCOMPRA NUMERIC (18,2)  ,
PROD_PVENTA NUMERIC (18,2),
PROD_STOCK INT ,
PROD_FECHAVEN DATE ,
PROD_IMG VARCHAR(MAX) ,
FECH_CREA DATETIME  ,
EST INT  ,

CONSTRAINT PROD_FK_SUC_ID
	FOREIGN KEY (SUC_ID)
	REFERENCES TM_SUCURSAL (SUC_ID),

CONSTRAINT PROD_FK_CAT_ID
	FOREIGN KEY (CAT_ID)
	REFERENCES TM_CATEGORIA (CAT_ID),

CONSTRAINT PROD_FK_UND_ID
	FOREIGN KEY (UND_ID)
	REFERENCES TM_UNIDAD (UND_ID),

CONSTRAINT PROD_FK_MON_ID
	FOREIGN KEY (MON_ID)
	REFERENCES TM_MONEDA (MON_ID),
)


CREATE TABLE TM_CLIENTE(
CLI_ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
EMP_ID INT ,
CLI_NOM VARCHAR (150) ,
CLI_RUC VARCHAR(150) ,
CLI_TEL VARCHAR(50) ,
CLI_DIRECC VARCHAR(150) ,
CLI_CORREO VARCHAR(150) , 
FECH_CREA DATETIME ,
EST INT ,

CONSTRAINT CLIE_FK_EMP_ID 
	FOREIGN KEY (EMP_ID)
	REFERENCES TM_EMPRESA (EMP_ID)
)


CREATE TABLE TM_PROVEEDOR(
PROV_ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
EMP_ID INT ,
PROV_NOM VARCHAR(150) ,
PROV_RUC VARCHAR(150) ,
PROV_TEL VARCHAR(50) ,
PROV_DIRECC VARCHAR(150) ,
PROV_CORREO VARCHAR(150) , 
FECH_CREA DATETIME ,
EST INT ,

CONSTRAINT PROV_FK_EMP_ID 
	FOREIGN KEY (EMP_ID)
	REFERENCES TM_EMPRESA (EMP_ID)
)