--#############################################
--LISTAR TODOS LOS REGISTROS POR SUCURSAL
CREATE PROCEDURE SP_L_EMPRESA_01
@COM_ID INT 
AS
BEGIN
	SELECT * FROM TM_EMPRESA
	WHERE
	COM_ID = @COM_ID
	AND
	EST = 1
END

--EJECUTAR EL PROCEDIMIENTO
--	EXEC SP_L_EMPRESA_01 @XX

--MODIFICAR EL PROCEDIMIENTO 
--	SP_HELPTEXT SP_L_EMPRESA_01

--#############################################
--OBTENER REGISTROS POR ID
CREATE PROCEDURE SP_L_EMPRESA_02
@EMP_ID INT
AS
BEGIN
	SELECT * FROM TM_EMPRESA
	WHERE
	EMP_ID = @EMP_ID
END

--#############################################
--ELIMINAR REGISTROS POR ID
CREATE PROCEDURE SP_D_EMPRESA_01
@EMP_ID INT
AS
BEGIN
	UPDATE TM_EMPRESA
	SET
		EST = 0
	WHERE 
		EMP_ID= @EMP_ID		
END


--#############################################
--INSERTAR NUEVO REGISTRO
CREATE PROCEDURE SP_I_EMPRESA_01
@COM_ID INT,
@EMP_NOM VARCHAR(150),
@EMP_RUC VARCHAR(150)
AS
BEGIN
	INSERT INTO TM_EMPRESA 
	(EMP_NOM,EMP_RUC, FECH_CREA, EST)
	VALUES
	(@EMP_NOM,@EMP_RUC, GETDATE(), 1)
END

SELECT * FROM TM_EMPRESA
--#############################################
--ACTUALIZAR REGISTRO
CREATE PROCEDURE SP_U_EMPRESA_01
@EMP_ID INT,
@COM_ID INT,
@EMP_NOM VARCHAR(150),
@EMP_RUC VARCHAR(150)
AS
BEGIN
	UPDATE TM_EMPRESA
	SET
		COM_ID = @COM_ID,
		EMP_NOM = @EMP_NOM,
		EMP_RUC = @EMP_RUC
	WHERE
		EMP_ID = @EMP_ID
END

SELECT * FROM TM_EMPRESA