--#############################################
--LISTAR TODOS LOS REGISTROS POR SUCURSAL
CREATE PROCEDURE SP_L_MONEDA_01
@SUC_ID INT
AS
BEGIN
	SELECT * FROM TM_MONEDA
	WHERE
	SUC_ID = @SUC_ID
	AND EST = 1
END

--EJECUTAR EL PROCEDIMIENTO
--	EXEC SP_L_MONEDA_01 @XX

--MODIFICAR EL PROCEDIMIENTO 
--	SP_HELPTEXT SP_L_MONEDA_01

--#############################################
--OBTENER REGISTROS POR ID
CREATE PROCEDURE SP_L_MONEDA_02
@MON_ID INT
AS
BEGIN
	SELECT * FROM TM_MONEDA
	WHERE
	MON_ID = @MON_ID
END

--#############################################
--ELIMINAR REGISTROS POR ID
CREATE PROCEDURE SP_D_MONEDA_01
@MON_ID INT
AS
BEGIN
	UPDATE TM_MONEDA
	SET
		EST = 0
	WHERE 
		MON_ID= @MON_ID		
END


--#############################################
--INSERTAR NUEVO REGISTRO
CREATE PROCEDURE SP_I_MONEDA_01
@SUC_ID INT,
@MON_NOM VARCHAR(150)
AS
BEGIN
	INSERT INTO TM_MONEDA 
	(SUC_ID, MON_NOM, FECH_CREA, EST)
	VALUES
	(@SUC_ID, @MON_NOM, GETDATE(), 1)
END


--#############################################
--ACTUALIZAR REGISTRO
CREATE PROCEDURE SP_U_MONEDA_01
@MON_ID INT,
@SUC_ID INT,
@MON_NOM VARCHAR(150)
AS
BEGIN
	UPDATE TM_MONEDA
	SET
		SUC_ID = @SUC_ID,
		MON_NOM = @MON_NOM
	WHERE
		MON_ID = @MON_ID
END

SELECT * FROM TM_MONEDA