use CompraVenta
--#############################################
--LISTAR TODOS LOS REGISTROS POR SUCURSAL
CREATE PROCEDURE SP_L_PRODUCTO_01
@SUC_ID INT
AS
BEGIN
	SELECT * FROM TM_PRODUCTO
	WHERE
	SUC_ID = @SUC_ID
	AND EST = 1
END

--EJECUTAR EL PROCEDIMIENTO
--	EXEC SP_L_PRODUCTO_01 @XX

--MODIFICAR EL PROCEDIMIENTO 
--	SP_HELPTEXT SP_L_PRODUCTO_01

--#############################################
--OBTENER REGISTROS POR ID
CREATE PROCEDURE SP_L_PRODUCTO_02
@PROD_ID INT
AS
BEGIN
	SELECT * FROM TM_PRODUCTO
	WHERE
	PROD_ID = @PROD_ID
END

--#############################################
--ELIMINAR REGISTROS POR ID
CREATE PROCEDURE SP_D_PRODUCTO_01
@PROD_ID INT
AS
BEGIN
	UPDATE TM_PRODUCTO
	SET
		EST = 0
	WHERE 
		PROD_ID= @PROD_ID		
END


--#############################################
--INSERTAR NUEVO REGISTRO
CREATE PROCEDURE SP_I_PRODUCTO_01
@SUC_ID INT,
@CAT_ID INT,
@PROD_NOM VARCHAR(150),
@PROD_DESCRIP VARCHAR(150),
@UND_ID INT,
@MON_ID INT,
@PROD_PCOMPRA NUMERIC(18,2),
@PROD_PVENTA NUMERIC(18,2),
@PROD_STOCK INT,
@PROD_FECHAVEN DATE,
@PROD_IMG VARCHAR(MAX)

AS
BEGIN
	INSERT INTO TM_PRODUCTO 
	(SUC_ID, CAT_ID, PROD_NOM, PROD_DESCRIP, UND_ID, MON_ID, PROD_PCOMPRA, PROD_PVENTA, PROD_STOCK, PROD_FECHAVEN, PROD_IMG, FECH_CREA, EST)
	VALUES
	(@SUC_ID , @CAT_ID, @PROD_NOM, @PROD_DESCRIP, @UND_ID, @MON_ID, @PROD_PCOMPRA, @PROD_PVENTA, @PROD_STOCK, @PROD_FECHAVEN, @PROD_IMG, GETDATE(), 1)
END


--#############################################
--ACTUALIZAR REGISTRO
CREATE PROCEDURE SP_U_PRODUCTO_01
@PROD_ID INT,
@SUC_ID INT,
@CAT_ID INT,
@PROD_NOM VARCHAR(150),
@PROD_DESCRIP VARCHAR(150),
@UND_ID INT,
@MON_ID INT,
@PROD_PCOMPRA NUMERIC(18,2),
@PROD_PVENTA NUMERIC(18,2),
@PROD_STOCK INT,
@PROD_FECHAVEN DATE,
@PROD_IMG VARCHAR(MAX)
AS
BEGIN
	UPDATE TM_PRODUCTO
	SET
		SUC_ID = @SUC_ID, 
		CAT_ID = @CAT_ID, 
		PROD_NOM = @PROD_NOM, 
		PROD_DESCRIP = @PROD_DESCRIP, 
		UND_ID = @UND_ID, 
		MON_ID = @MON_ID, 
		PROD_PCOMPRA = @PROD_PCOMPRA, 
		PROD_PVENTA = @PROD_PVENTA, 
		PROD_STOCK = @PROD_STOCK, 
		PROD_FECHAVEN = @PROD_FECHAVEN, 
		PROD_IMG = @PROD_IMG

	WHERE
		PROD_ID = @PROD_ID
END

SELECT * FROM TM_PRODUCTO