use CompraVenta
--#############################################
--LISTAR TODOS LOS REGISTROS POR SUCURSAL
CREATE PROCEDURE SP_L_PROVEEDOR_01
@EMP_ID INT
AS
BEGIN
	SELECT * FROM TM_PROVEEDOR
	WHERE
	EMP_ID = @EMP_ID
	AND EST = 1
END

--EJECUTAR EL PROCEDIMIENTO
--	EXEC SP_L_PROVEEDOR_01 @XX

--MODIFICAR EL PROCEDIMIENTO 
--	SP_HELPTEXT SP_L_PROVEEDOR_01

--#############################################
--OBTENER REGISTROS POR ID
CREATE PROCEDURE SP_L_PROVEEDOR_02
@PROV_ID INT
AS
BEGIN
	SELECT * FROM TM_PROVEEDOR
	WHERE
	PROV_ID = @PROV_ID
END

--#############################################
--ELIMINAR REGISTROS POR ID
CREATE PROCEDURE SP_D_PROVEEDOR_01
@PROV_ID INT
AS
BEGIN
	UPDATE TM_PROVEEDOR
	SET
		EST = 0
	WHERE 
		PROV_ID= @PROV_ID		
END


--#############################################
--INSERTAR NUEVO REGISTRO
CREATE PROCEDURE SP_I_PROVEEDOR_01
@EMP_ID INT,
@PROV_NOM VARCHAR(150),
@PROV_RUC INT,
@PROV_TEL VARCHAR(150),
@PROV_DIRECC VARCHAR(150),
@PROV_CORREO VARCHAR(150)

AS
BEGIN
	INSERT INTO TM_PROVEEDOR 
	(EMP_ID, PROV_NOM, PROV_RUC, PROV_TEL, PROV_DIRECC, PROV_CORREO,FECH_CREA, EST)
	VALUES
	(@EMP_ID, @PROV_NOM,@PROV_RUC, @PROV_TEL, @PROV_DIRECC, @PROV_CORREO,GETDATE(), 1)
END


--#############################################
--ACTUALIZAR REGISTRO
CREATE PROCEDURE SP_U_PROVEEDOR_01
@PROV_ID INT,
@EMP_ID INT,
@PROV_NOM VARCHAR(150),
@PROV_RUC VARCHAR(50),
@PROV_TEL VARCHAR(150),
@PROV_DIRECC VARCHAR(150),
@PROV_CORREO VARCHAR(150)
AS
BEGIN
	UPDATE TM_PROVEEDOR
	SET
		EMP_ID = @EMP_ID,
		PROV_NOM = @PROV_NOM,
		PROV_RUC = @PROV_RUC,
		PROV_TEL = @PROV_TEL,
		PROV_DIRECC = @PROV_DIRECC,
		PROV_CORREO = @PROV_CORREO

	WHERE
		PROV_ID = @PROV_ID
END

SELECT * FROM TM_PROVEEDOR